# Generated by Django 6.0.6 on 2026-06-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='preferred_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='preferred_slot',
            field=models.CharField(choices=[('morning', 'Morning (9:00 AM - 12:00 PM)'), ('afternoon', 'Afternoon (12:00 PM - 4:00 PM)'), ('evening', 'Evening (4:00 PM - 7:00 PM)')], default='morning', max_length=20),
        ),
    ]
